import UnitType from '@/domain/unit-type'

export const DS = {
  1: {
    stars: 2,
    territories: {
      top: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERINITIATE', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'NUTEGUNRAY' ] },
          2: { active: true, units: [ 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRANDMOFFTARKIN', 'NUTEGUNRAY', 'SUNFAC', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD', 'BOBAFETT', 'DENGAR', 'GREEDO', 'IG88', 'CADBANE' ] },
          3: { active: true, units: [ 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'MAGMATROOPER' ] },
          4: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'POGGLETHELESSER', 'NUTEGUNRAY', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER' ] },
          5: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'GARSAXON', 'DEATHTROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT', 'TIEFIGHTERPILOT' ] },
          6: { active: true, units: [ 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'TALIA', 'STORMTROOPER', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERINITIATE', 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER' ] },
          2: { active: true, units: [ 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC', 'GARSAXON', 'DEATHTROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT' ] },
          3: { active: true, units: [ 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERINITIATE', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC' ] },
          4: { active: true, units: [ 'STORMTROOPER', 'FIRSTORDERTIEPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'NUTEGUNRAY', 'B1BATTLEDROIDV2', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'MAGMATROOPER' ] },
          5: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'POGGLETHELESSER', 'NUTEGUNRAY', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'BOBAFETT', 'DENGAR', 'GREEDO', 'IG88', 'BOSSK' ] },
          6: { active: true, units: [ 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'STORMTROOPER', 'FIRSTORDERTIEPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'BOBAFETT', 'TUSKENSHAMAN', 'TUSKENRAIDER', 'HUMANTHUG', 'BOSSK' ] }
        }
      }
    }
  },
  2: {
    stars: 3,
    territories: {
      top: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'POGGLETHELESSER', 'COUNTDOOKU', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'RANGETROOPER', 'STORMTROOPER', 'MAGMATROOPER' ] },
          2: { active: true, units: [ 'NUTEGUNRAY', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT', 'STORMTROOPER', 'MAGMATROOPER', 'DEATHTROOPER' ] },
          3: { active: true, units: [ 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRANDMOFFTARKIN', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC', 'GARSAXON', 'IMPERIALSUPERCOMMANDO', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT' ] },
          4: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'B1BATTLEDROIDV2', 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER' ] },
          5: { active: true, units: [ 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER' ] },
          6: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'TALIA', 'NUTEGUNRAY', 'B2SUPERBATTLEDROID', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'TALIA', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC' ] },
          2: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'B1BATTLEDROIDV2', 'NUTEGUNRAY', 'DROIDEKA', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD' ] },
          3: { active: true, units: [ 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER', 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'URORRURRR', 'TUSKENSHAMAN', 'TUSKENRAIDER', 'HUMANTHUG', 'GAMORREANGUARD' ] },
          4: { active: true, units: [ 'POGGLETHELESSER', 'COUNTDOOKU', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'MAGMATROOPER', 'GARSAXON', 'DEATHTROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT' ] },
          5: { active: true, units: [ 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'DIRECTORKRENNIC', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER', 'DEATHTROOPER' ] },
          6: { active: true, units: [ 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'MAGMATROOPER', 'DEATHTROOPER', 'GRANDMOFFTARKIN', 'ROYALGUARD', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'MAGMATROOPER' ] }
        }
      }
    }
  },
  3: {
    stars: 4,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'JEDISTARFIGHTERAHSOKATANO', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'PHANTOM2', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'SITHINFILTRATOR', 'SLAVE1', 'PHANTOM2', 'ARC170CLONESERGEANT', 'UWINGSCARIF', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2' ] },
          2: { active: true, units: [ 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'TIEADVANCED', 'TIESILENCER', 'ARC170CLONESERGEANT', 'JEDISTARFIGHTERAHSOKATANO', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER', 'XWINGRED2', 'XWINGBLACKONE', 'BLADEOFDORIN', 'GHOST', 'TIESILENCER' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'GAUNTLETSTARFIGHTER', 'TIEFIGHTERFIRSTORDER', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'SITHINFILTRATOR', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'TIESILENCER', 'SLAVE1' ] },
          4: { active: true, units: [ 'XWINGRED3', 'GAUNTLETSTARFIGHTER', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH' ] },
          5: { active: true, units: [ 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'UMBARANSTARFIGHTER', 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'UMBARANSTARFIGHTER' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'UWINGSCARIF', 'SLAVE1', 'UWINGROGUEONE', 'EBONHAWK', 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'UMBARANSTARFIGHTER', 'ARC170CLONESERGEANT', 'BLADEOFDORIN' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'TALIA', 'NUTEGUNRAY', 'B2SUPERBATTLEDROID', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN' ] },
          2: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'NUTEGUNRAY', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC' ] },
          3: { active: true, units: [ 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'POGGLETHELESSER', 'B2SUPERBATTLEDROID', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'GARSAXON', 'DEATHTROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT' ] },
          4: { active: true, units: [ 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'TALIA', 'ASAJVENTRESS', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE' ] },
          5: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'EMPERORPALPATINE', 'ROYALGUARD', 'GARSAXON', 'TIEFIGHTERPILOT', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER' ] },
          6: { active: true, units: [ 'GRIEVOUS', 'MAGNAGUARD', 'COUNTDOOKU', 'NUTEGUNRAY', 'POGGLETHELESSER', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'NUTEGUNRAY', 'TUSKENRAIDER', 'GEONOSIANSOLDIER', 'GEONOSIANSPY', 'URORRURRR' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GARSAXON', 'IMPERIALSUPERCOMMANDO', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'URORRURRR', 'TUSKENSHAMAN', 'TUSKENRAIDER', 'HUMANTHUG', 'GRANDMOFFTARKIN' ] },
          2: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC', 'POGGLETHELESSER', 'ASAJVENTRESS', 'IG86SENTINELDROID', 'MAGNAGUARD', 'SUNFAC' ] },
          3: { active: true, units: [ 'DAKA', 'ASAJVENTRESS', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERINITIATE', 'TALIA', 'COUNTDOOKU', 'GEONOSIANSPY', 'GEONOSIANSOLDIER', 'POGGLETHELESSER', 'SUNFAC', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN' ] },
          4: { active: true, units: [ 'TALIA', 'ASAJVENTRESS', 'DAKA', 'SAVAGEOPRESS', 'NIGHTSISTERINITIATE', 'NUTEGUNRAY', 'JANGOFETT', 'IG86SENTINELDROID', 'COUNTDOOKU', 'MAGNAGUARD', 'GRANDMOFFTARKIN', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'DIRECTORKRENNIC', 'GARSAXON' ] },
          5: { active: true, units: [ 'EMPERORPALPATINE', 'GRIEVOUS', 'DARTHNIHILUS', 'MAUL', 'SITHTROOPER', 'GARSAXON', 'IMPERIALSUPERCOMMANDO', 'ROYALGUARD', 'DIRECTORKRENNIC', 'TIEFIGHTERPILOT', 'HK47', 'POGGLETHELESSER', 'IG86SENTINELDROID', 'MAGNAGUARD', 'GARSAXON' ] },
          6: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'TIEFIGHTERPILOT', 'ROYALGUARD', 'GARSAXON', 'GRANDMOFFTARKIN', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'COUNTDOOKU', 'SITHTROOPER' ] }
        }
      }
    }
  },
  4: {
    stars: 5,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'TIEREAPER', 'TIEADVANCED', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX' ] },
          2: { active: true, units: [ 'SITHINFILTRATOR', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'GEONOSIANSTARFIGHTER3', 'SLAVE1', 'XWINGRED3', 'MILLENNIUMFALCONEP7', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST' ] },
          3: { active: true, units: [ 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2' ] },
          4: { active: true, units: [ 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'BLADEOFDORIN', 'GHOST', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX' ] },
          5: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'HOUNDSTOOTH', 'PHANTOM2', 'COMMANDSHUTTLE', 'GAUNTLETSTARFIGHTER', 'UWINGROGUEONE', 'ARC170CLONESERGEANT', 'ARC170REX', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'MAGNAGUARD', 'MAUL', 'CADBANE', 'ZAMWESELL', 'ASAJVENTRESS', 'VADER', 'STORMTROOPER', 'ROYALGUARD', 'MAGMATROOPER', 'IMPERIALPROBEDROID', 'MOTHERTALZIN', 'TALIA', 'MAUL', 'SAVAGEOPRESS', 'DAKA' ] },
          2: { active: true, units: [ 'CADBANE', 'MAGNAGUARD', 'DARTHSIDIOUS', 'GEONOSIANSOLDIER', 'GEONOSIANSPY', 'GRANDMOFFTARKIN', 'SHORETROOPER', 'STORMTROOPER', 'IMPERIALPROBEDROID', 'ROYALGUARD', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERSPIRIT', 'TALIA', 'DAKA' ] },
          3: { active: true, units: [ 'DARTHSION', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHMARAUDER', 'SITHTROOPER', 'COUNTDOOKU', 'POGGLETHELESSER', 'NUTEGUNRAY', 'SUNFAC', 'ASAJVENTRESS', 'DARTHSIDIOUS', 'IG86SENTINELDROID', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'FIRSTORDERTROOPER' ] },
          4: { active: true, units: [ 'CADBANE', 'JANGOFETT', 'ZAMWESELL', 'IG88', 'EMBO', 'PHASMA', 'KYLOREN', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEREXECUTIONER', 'COLONELSTARCK', 'RANGETROOPER', 'STORMTROOPER', 'DEATHTROOPER', 'MAGMATROOPER' ] },
          5: { active: true, units: [ 'GARSAXON', 'HUMANTHUG', 'AURRA_SING', 'IG88', 'IMPERIALPROBEDROID', 'JANGOFETT', 'ZAMWESELL', 'ASAJVENTRESS', 'BOBAFETT', 'GREEDO', 'GEONOSIANSOLDIER', 'GEONOSIANSPY', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'URORRURRR' ] },
          6: { active: true, units: [ 'BASTILASHANDARK', 'DARTHNIHILUS', 'SITHMARAUDER', 'SITHTROOPER', 'HK47', 'FIRSTORDEREXECUTIONER', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDERTIEPILOT', 'PHASMA', 'NUTEGUNRAY', 'SUNFAC', 'POGGLETHELESSER', 'DROIDEKA', 'B1BATTLEDROIDV2' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRANDMOFFTARKIN', 'DEATHTROOPER', 'STORMTROOPER', 'TIEFIGHTERPILOT', 'VADER', 'MOTHERTALZIN', 'MAUL', 'TALIA', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'NIGHTSISTERSPIRIT', 'NIGHTSISTERZOMBIE', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE' ] },
          2: { active: true, units: [ 'IMPERIALSUPERCOMMANDO', 'VADER', 'BOBAFETT', 'GREEDO', 'BOSSK', 'TIEFIGHTERPILOT', 'VADER', 'COLONELSTARCK', 'SHORETROOPER', 'IMPERIALPROBEDROID', 'NIGHTSISTERINITIATE', 'NIGHTSISTERSPIRIT', 'MOTHERTALZIN', 'TALIA', 'SAVAGEOPRESS' ] },
          3: { active: true, units: [ 'FIRSTORDEROFFICERMALE', 'FIRSTORDERTIEPILOT', 'FIRSTORDERTROOPER', 'KYLORENUNMASKED', 'HUMANTHUG', 'FIRSTORDERTROOPER', 'KYLOREN', 'KYLORENUNMASKED', 'DARTHSIDIOUS', 'BOBAFETT', 'BOBAFETT', 'GREEDO', 'HK47', 'IG88', 'DENGAR' ] },
          4: { active: true, units: [ 'GRIEVOUS', 'MAGNAGUARD', 'DARTHSIDIOUS', 'GAMORREANGUARD', 'GREEDO', 'MOTHERTALZIN', 'MAUL', 'KYLORENUNMASKED', 'TUSKENSHAMAN', 'URORRURRR', 'CADBANE', 'IG86SENTINELDROID', 'MAGNAGUARD', 'COUNTDOOKU', 'B2SUPERBATTLEDROID' ] },
          5: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'DARTHNIHILUS', 'DARTHSION', 'HK47', 'KYLORENUNMASKED', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'GREEDO', 'HUMANTHUG', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRANDMOFFTARKIN' ] },
          6: { active: true, units: [ 'GRANDMOFFTARKIN', 'GARSAXON', 'BOBAFETT', 'STORMTROOPER', 'RANGETROOPER', 'DARTHSIDIOUS', 'MAUL', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'URORRURRR', 'GRIEVOUS', 'DROIDEKA', 'B1BATTLEDROIDV2', 'B2SUPERBATTLEDROID', 'IG86SENTINELDROID' ] }
        }
      }
    }
  },
  5: {
    stars: 6,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'ARC170CLONESERGEANT', 'ARC170REX', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'GEONOSIANSTARFIGHTER2', 'TIEADVANCED', 'TIEFIGHTERFOSF' ] },
          2: { active: true, units: [ 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'MILLENNIUMFALCON', 'GHOST', 'TIESILENCER', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN' ] },
          4: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX' ] },
          5: { active: true, units: [ 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'SITHINFILTRATOR', 'SLAVE1', 'XWINGRED3', 'MILLENNIUMFALCONEP7', 'JEDISTARFIGHTERANAKIN', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'HOUNDSTOOTH', 'PHANTOM2', 'COMMANDSHUTTLE', 'GAUNTLETSTARFIGHTER', 'UWINGROGUEONE' ] },
          6: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'SITHFIGHTER', 'SITHBOMBER', 'EBONHAWK', 'XANADUBLOOD', 'IG2000', 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'PHASMA', 'KYLOREN', 'FIRSTORDERTIEPILOT', 'FIRSTORDEREXECUTIONER', 'FIRSTORDERSPECIALFORCESPILOT', 'MOTHERTALZIN', 'TALIA', 'MAUL', 'SAVAGEOPRESS', 'DAKA', 'EMPERORPALPATINE', 'TIEFIGHTERPILOT', 'VADER', 'DIRECTORKRENNIC', 'DEATHTROOPER' ] },
          2: { active: true, units: [ 'ASAJVENTRESS', 'MAGNAGUARD', 'DARTHSIDIOUS', 'GEONOSIANSOLDIER', 'GEONOSIANSPY', 'VADER', 'EMPERORPALPATINE', 'ROYALGUARD', 'GRANDADMIRALTHRAWN', 'IMPERIALPROBEDROID', 'NIGHTSISTERINITIATE', 'MOTHERTALZIN', 'TALIA', 'SAVAGEOPRESS', 'DAKA' ] },
          3: { active: true, units: [ 'IMPERIALSUPERCOMMANDO', 'EMPERORPALPATINE', 'GRANDADMIRALTHRAWN', 'RANGETROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRANDMOFFTARKIN', 'TIEFIGHTERPILOT', 'VADER', 'COLONELSTARCK', 'SHORETROOPER', 'IMPERIALPROBEDROID' ] },
          4: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'HK47', 'SITHTROOPER', 'SITHASSASSIN', 'COLONELSTARCK', 'SHORETROOPER', 'GRANDADMIRALTHRAWN', 'WAMPA', 'ROYALGUARD', 'NIGHTSISTERINITIATE', 'DAKA', 'NIGHTSISTERSPIRIT', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE' ] },
          5: { active: true, units: [ 'DARTHTRAYA', 'SITHASSASSIN', 'SITHMARAUDER', 'SITHTROOPER', 'DARTHSION', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'FIRSTORDERTIEPILOT', 'FIRSTORDERTROOPER', 'VEERS', 'COLONELSTARCK', 'RANGETROOPER', 'WAMPA', 'SNOWTROOPER' ] },
          6: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'SITHMARAUDER', 'SITHTROOPER', 'SITHASSASSIN', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'PHASMA', 'FIRSTORDEREXECUTIONER', 'FIRSTORDEROFFICERMALE', 'DROIDEKA', 'COUNTDOOKU', 'B1BATTLEDROIDV2', 'DARTHSIDIOUS', 'ASAJVENTRESS' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRANDMOFFTARKIN', 'COLONELSTARCK', 'EMPERORPALPATINE', 'TIEFIGHTERPILOT', 'WAMPA', 'VEERS', 'SNOWTROOPER', 'ROYALGUARD', 'EMPERORPALPATINE', 'GRANDMOFFTARKIN', 'VEERS', 'SHORETROOPER', 'SNOWTROOPER', 'TIEFIGHTERPILOT', 'IMPERIALSUPERCOMMANDO' ] },
          2: { active: true, units: [ 'GRANDMOFFTARKIN', 'EMPERORPALPATINE', 'MAGMATROOPER', 'STORMTROOPER', 'RANGETROOPER', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'FIRSTORDERTROOPER', 'IG86SENTINELDROID', 'GRIEVOUS', 'DROIDEKA', 'B1BATTLEDROIDV2', 'B2SUPERBATTLEDROID', 'MAGNAGUARD' ] },
          3: { active: true, units: [ 'TALIA', 'MAUL', 'ASAJVENTRESS', 'MAGNAGUARD', 'DROIDEKA', 'TUSKENRAIDER', 'STORMTROOPER', 'ROYALGUARD', 'SNOWTROOPER', 'MAGMATROOPER', 'DARTHSION', 'DARTHTRAYA', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHMARAUDER' ] },
          4: { active: true, units: [ 'B1BATTLEDROIDV2', 'DROIDEKA', 'POGGLETHELESSER', 'NUTEGUNRAY', 'B2SUPERBATTLEDROID', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'WAMPA', 'VADER', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'URORRURRR' ] },
          5: { active: true, units: [ 'SUNFAC', 'B1BATTLEDROIDV2', 'DROIDEKA', 'MAGNAGUARD', 'MAUL', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERZOMBIE', 'TALIA', 'NIGHTSISTERSPIRIT', 'RANGETROOPER', 'TUSKENRAIDER', 'RANGETROOPER', 'URORRURRR', 'TIEFIGHTERPILOT', 'GEONOSIANSOLDIER' ] },
          6: { active: true, units: [ 'TUSKENSHAMAN', 'URORRURRR', 'TUSKENRAIDER', 'GAMORREANGUARD', 'HUMANTHUG', 'SITHMARAUDER', 'GEONOSIANSOLDIER', 'URORRURRR', 'TUSKENRAIDER', 'IG86SENTINELDROID', 'B1BATTLEDROIDV2', 'IG86SENTINELDROID', 'GEONOSIANSOLDIER', 'COUNTDOOKU', 'B2SUPERBATTLEDROID' ] }
        }
      }
    }
  },
  6: {
    stars: 7,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'EMPERORSSHUTTLE', 'SLAVE1', 'TIEADVANCED' ] },
          2: { active: true, units: [ 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'XWINGRED3', 'UWINGSCARIF', 'ARC170CLONESERGEANT', 'MILLENNIUMFALCON', 'GHOST', 'HOUNDSTOOTH', 'EBONHAWK', 'SLAVE1', 'UMBARANSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR' ] },
          3: { active: true, units: [ 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'SITHINFILTRATOR', 'SLAVE1', 'XWINGRED2', 'XWINGBLACKONE', 'MILLENNIUMFALCON', 'GHOST', 'TIESILENCER', 'MILLENNIUMFALCON', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCONPRISTINE', 'PHANTOM2', 'GHOST' ] },
          4: { active: true, units: [ 'TIEFIGHTERIMPERIAL', 'TIESILENCER', 'TIEFIGHTERFIRSTORDER', 'TIEADVANCED', 'TIEREAPER', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'GHOST', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCON', 'EBONHAWK', 'MILLENNIUMFALCONPRISTINE' ] },
          5: { active: true, units: [ 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER', 'GEONOSIANSTARFIGHTER3', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'SITHBOMBER', 'XANADUBLOOD', 'IG2000', 'SITHFIGHTER', 'SITHINFILTRATOR' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERFOSF', 'COMMANDSHUTTLE', 'TIESILENCER', 'MILLENNIUMFALCONEP7' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'PHASMA', 'KYLOREN', 'FIRSTORDERTROOPER', 'FIRSTORDEREXECUTIONER', 'FIRSTORDERSPECIALFORCESPILOT', 'COUNTDOOKU', 'TALIA', 'ZAMWESELL', 'SAVAGEOPRESS', 'DAKA', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDEREXECUTIONER', 'KYLOREN', 'FIRSTORDERTIEPILOT', 'FIRSTORDERTROOPER' ] },
          2: { active: true, units: [ 'EMPERORPALPATINE', 'TIEFIGHTERPILOT', 'DEATHTROOPER', 'DIRECTORKRENNIC', 'IMPERIALPROBEDROID', 'EMPERORPALPATINE', 'DEATHTROOPER', 'GRANDADMIRALTHRAWN', 'WAMPA', 'ZAMWESELL', 'NIGHTSISTERINITIATE', 'NIGHTSISTERSPIRIT', 'TALIA', 'SAVAGEOPRESS', 'DAKA' ] },
          3: { active: true, units: [ 'JANGOFETT', 'COUNTDOOKU', 'NUTEGUNRAY', 'DARTHSIDIOUS', 'ASAJVENTRESS', 'JANGOFETT', 'ZAMWESELL', 'MAGNAGUARD', 'COUNTDOOKU', 'IG86SENTINELDROID', 'SUNFAC', 'GEONOSIANSOLDIER', 'IG86SENTINELDROID', 'GRIEVOUS', 'NIGHTSISTERSPIRIT' ] },
          4: { active: true, units: [ 'DARTHSION', 'DARTHTRAYA', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHMARAUDER', 'DENGAR', 'CADBANE', 'AURRA_SING', 'BOSSK', 'BOBAFETT', 'POGGLETHELESSER', 'NIGHTSISTERSPIRIT', 'NIGHTSISTERZOMBIE', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE' ] },
          5: { active: true, units: [ 'EMBO', 'DENGAR', 'BOBAFETT', 'WAMPA', 'CADBANE', 'DARTHTRAYA', 'SITHASSASSIN', 'CANDEROUSORDO', 'SITHTROOPER', 'DARTHSION', 'MAUL', 'TALIA', 'NIGHTSISTERSPIRIT', 'SAVAGEOPRESS', 'URORRURRR' ] },
          6: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'DARTHNIHILUS', 'SITHTROOPER', 'DARTHSION', 'GAMORREANGUARD', 'GARSAXON', 'GRANDADMIRALTHRAWN', 'WAMPA', 'SNOWTROOPER', 'B1BATTLEDROIDV2', 'DROIDEKA', 'POGGLETHELESSER', 'NUTEGUNRAY', 'B2SUPERBATTLEDROID' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'EMPERORPALPATINE', 'HUMANTHUG', 'DEATHTROOPER', 'MAGMATROOPER', 'ASAJVENTRESS', 'COUNTDOOKU', 'DARTHSIDIOUS', 'GRIEVOUS', 'WAMPA', 'EMPERORPALPATINE', 'VADER', 'GRANDADMIRALTHRAWN', 'SHORETROOPER', 'DEATHTROOPER' ] },
          2: { active: true, units: [ 'GRANDMOFFTARKIN', 'EMPERORPALPATINE', 'TIEFIGHTERPILOT', 'STORMTROOPER', 'GARSAXON', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDERTIEPILOT', 'FIRSTORDEREXECUTIONER', 'TUSKENSHAMAN', 'IG86SENTINELDROID', 'GRIEVOUS', 'COUNTDOOKU', 'B2SUPERBATTLEDROID' ] },
          3: { active: true, units: [ 'IMPERIALSUPERCOMMANDO', 'EMPERORPALPATINE', 'GRANDADMIRALTHRAWN', 'RANGETROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'GRANDADMIRALTHRAWN', 'HUMANTHUG', 'ROYALGUARD', 'VADER', 'GREEDO', 'DEATHTROOPER', 'TIEFIGHTERPILOT', 'RANGETROOPER' ] },
          4: { active: true, units: [ 'IG88', 'GREEDO', 'GAMORREANGUARD', 'HUMANTHUG', 'TUSKENRAIDER', 'SITHMARAUDER', 'DARTHSION', 'WAMPA', 'HK47', 'SITHASSASSIN', 'KYLORENUNMASKED', 'FIRSTORDEROFFICERMALE', 'NIGHTSISTERSPIRIT', 'DARTHTRAYA', 'TUSKENRAIDER' ] },
          5: { active: true, units: [ 'WAMPA', 'DENGAR', 'BOSSK', 'AURRA_SING', 'CADBANE', 'TUSKENSHAMAN', 'URORRURRR', 'TUSKENRAIDER', 'WAMPA', 'GARSAXON', 'MAGMATROOPER', 'SHORETROOPER', 'DEATHTROOPER', 'TIEFIGHTERPILOT', 'IMPERIALSUPERCOMMANDO' ] },
          6: { active: true, units: [ 'SUNFAC', 'B1BATTLEDROIDV2', 'DROIDEKA', 'MAGNAGUARD', 'MAUL', 'BASTILASHANDARK', 'CANDEROUSORDO', 'HK47', 'SITHTROOPER', 'DARTHTRAYA', 'GRIEVOUS', 'WAMPA', 'B1BATTLEDROIDV2', 'B2SUPERBATTLEDROID', 'NUTEGUNRAY' ] }
        }
      }
    }
  }
}

export const LS = {
  1: {
    stars: 2,
    territories: {
      top: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'PRINCESSLEIA', 'LUKESKYWALKER', 'LOBOT', 'STORMTROOPERHAN', 'ADMINISTRATORLANDO', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'AHSOKATANO', 'BARRISSOFFEE', 'FINN', 'POE', 'REY', 'RESISTANCETROOPER', 'RESISTANCEPILOT' ] },
          2: { active: true, units: [ 'PRINCESSLEIA', 'HOTHREBELSCOUT', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'HOTHREBELSOLDIER', 'JEDIKNIGHTCONSULAR', 'IMAGUNDI', 'OLDBENKENOBI', 'QUIGONJINN', 'PLOKOON', 'CHIEFNEBIT', 'DATHCHA', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER' ] },
          3: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'HOTHREBELSCOUT', 'FULCRUMAHSOKA', 'BISTAN', 'KITFISTO', 'JEDIKNIGHTCONSULAR', 'LUMINARAUNDULI', 'ADMIRALACKBAR', 'PAO', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'TEEBO', 'PAPLOO' ] },
          4: { active: true, units: [ 'JYNERSO', 'CASSIANANDOR', 'BAZEMALBUS', 'CHIRRUTIMWE', 'K2SO', 'IMAGUNDI', 'JEDIKNIGHTCONSULAR', 'OLDBENKENOBI', 'QUIGONJINN', 'PLOKOON', 'CLONEWARSCHEWBACCA', 'CORUSCANTUNDERWORLDPOLICE', 'CLONESERGEANTPHASEI', 'ANAKINKNIGHT', 'AHSOKATANO' ] },
          5: { active: true, units: [ 'BODHIROOK', 'PAO', 'BISTAN', 'CASSIANANDOR', 'K2SO', 'HOTHREBELSOLDIER', 'JEDIKNIGHTCONSULAR', 'AHSOKATANO', 'AAYLASECURA', 'MACEWINDU', 'TEEBO', 'EWOKSCOUT', 'PAPLOO', 'LOGRAY', 'EWOKELDER' ] },
          6: { active: true, units: [ 'JYNERSO', 'BODHIROOK', 'PAO', 'BISTAN', 'SCARIFREBEL', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'EETHKOTH', 'BARRISSOFFEE', 'CC2224', 'CT210408', 'CT5555', 'CLONESERGEANTPHASEI', 'CT7567' ] }
        }
      }
    }
  },
  2: {
    stars: 3,
    territories: {
      top: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'CHOPPERS3', 'FULCRUMAHSOKA', 'OLDBENKENOBI', 'HOTHREBELSCOUT', 'JEDIKNIGHTCONSULAR', 'OLDBENKENOBI', 'HOTHREBELSOLDIER', 'PLOKOON', 'TEEBO', 'EWOKSCOUT', 'PAPLOO', 'CHIEFCHIRPA', 'EWOKELDER' ] },
          2: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'LUKESKYWALKER', 'HOTHREBELSOLDIER', 'ADMINISTRATORLANDO', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'EETHKOTH', 'BARRISSOFFEE', 'CLONEWARSCHEWBACCA', 'KITFISTO', 'CLONESERGEANTPHASEI', 'ANAKINKNIGHT', 'AHSOKATANO' ] },
          3: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'ZEBS3', 'EZRABRIDGERS3', 'CHOPPERS3', 'FINN', 'POE', 'REY', 'ADMIRALACKBAR', 'AHSOKATANO', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'TEEBO', 'PAPLOO' ] },
          4: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'CHOPPERS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'MACEWINDU', 'ADMIRALACKBAR', 'JEDIKNIGHTGUARDIAN', 'LUMINARAUNDULI', 'BARRISSOFFEE', 'CHIEFNEBIT', 'DATHCHA', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER' ] },
          5: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'ZEBS3', 'FULCRUMAHSOKA', 'LUKESKYWALKER', 'KITFISTO', 'LUMINARAUNDULI', 'QUIGONJINN', 'IMAGUNDI', 'AHSOKATANO', 'CC2224', 'CT210408', 'CT5555', 'CLONESERGEANTPHASEI', 'CT7567' ] },
          6: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'ZEBS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'IMAGUNDI', 'JEDIKNIGHTCONSULAR', 'OLDBENKENOBI', 'QUIGONJINN', 'PLOKOON', 'FINN', 'POE', 'REY', 'RESISTANCETROOPER', 'RESISTANCEPILOT' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'ZEBS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'MACEWINDU', 'JEDIKNIGHTCONSULAR', 'OLDBENKENOBI', 'QUIGONJINN', 'PLOKOON', 'FINN', 'POE', 'REY', 'RESISTANCETROOPER', 'RESISTANCEPILOT' ] },
          2: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'CHOPPERS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'AAYLASECURA', 'BARRISSOFFEE', 'CHIEFNEBIT', 'DATHCHA', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER' ] },
          3: { active: true, units: [ 'PRINCESSLEIA', 'ADMINISTRATORLANDO', 'LUKESKYWALKER', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'IMAGUNDI', 'JEDIKNIGHTCONSULAR', 'OLDBENKENOBI', 'QUIGONJINN', 'PLOKOON', 'TEEBO', 'EWOKSCOUT', 'PAPLOO', 'CHIEFCHIRPA', 'EWOKELDER' ] },
          4: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'LOBOT', 'UGNAUGHT', 'ADMINISTRATORLANDO', 'HOTHREBELSCOUT', 'HOTHREBELSOLDIER', 'PRINCESSLEIA', 'BIGGSDARKLIGHTER', 'FULCRUMAHSOKA', 'CC2224', 'CT210408', 'CT5555', 'CLONESERGEANTPHASEI', 'CT7567' ] },
          5: { active: true, units: [ 'HOTHREBELSOLDIER', 'LOBOT', 'LUKESKYWALKER', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'SABINEWRENS3', 'CHOPPERS3', 'ZEBS3', 'HOTHREBELSCOUT', 'AHSOKATANO', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'TEEBO', 'PAPLOO' ] },
          6: { active: true, units: [ 'WEDGEANTILLES', 'HOTHREBELSOLDIER', 'LOBOT', 'HOTHREBELSCOUT', 'ADMINISTRATORLANDO', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'AAYLASECURA', 'BARRISSOFFEE', 'CLONEWARSCHEWBACCA', 'CORUSCANTUNDERWORLDPOLICE', 'CLONESERGEANTPHASEI', 'ANAKINKNIGHT', 'AHSOKATANO' ] }
        }
      }
    }
  },
  3: {
    stars: 4,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'JEDISTARFIGHTERAHSOKATANO', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'PHANTOM2', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'SITHINFILTRATOR', 'SLAVE1', 'PHANTOM2', 'ARC170CLONESERGEANT', 'UWINGSCARIF', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2' ] },
          2: { active: true, units: [ 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'TIEADVANCED', 'TIESILENCER', 'ARC170CLONESERGEANT', 'JEDISTARFIGHTERAHSOKATANO', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER', 'XWINGRED2', 'XWINGBLACKONE', 'BLADEOFDORIN', 'GHOST', 'TIESILENCER' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'GAUNTLETSTARFIGHTER', 'TIEFIGHTERFIRSTORDER', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'SITHINFILTRATOR', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'TIESILENCER', 'SLAVE1' ] },
          4: { active: true, units: [ 'XWINGRED3', 'GAUNTLETSTARFIGHTER', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH' ] },
          5: { active: true, units: [ 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'UMBARANSTARFIGHTER', 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'UMBARANSTARFIGHTER' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'UWINGSCARIF', 'SLAVE1', 'UWINGROGUEONE', 'EBONHAWK', 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'UMBARANSTARFIGHTER', 'ARC170CLONESERGEANT', 'BLADEOFDORIN' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'LOBOT', 'FULCRUMAHSOKA', 'ADMINISTRATORLANDO', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'LUMINARAUNDULI', 'AHSOKATANO', 'TEEBO', 'EWOKSCOUT', 'PAPLOO', 'LOGRAY', 'EWOKELDER' ] },
          2: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'ZEBS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'LUMINARAUNDULI', 'BARRISSOFFEE', 'CLONEWARSCHEWBACCA', 'CORUSCANTUNDERWORLDPOLICE', 'CLONESERGEANTPHASEI', 'ANAKINKNIGHT', 'AHSOKATANO' ] },
          3: { active: true, units: [ 'LUKESKYWALKER', 'OLDBENKENOBI', 'ADMINISTRATORLANDO', 'HERASYNDULLAS3', 'PRINCESSLEIA', 'GRANDMASTERYODA', 'MACEWINDU', 'LUMINARAUNDULI', 'IMAGUNDI', 'PLOKOON', 'FINN', 'POE', 'REY', 'RESISTANCETROOPER', 'RESISTANCEPILOT' ] },
          4: { active: true, units: [ 'ADMIRALACKBAR', 'BIGGSDARKLIGHTER', 'STORMTROOPERHAN', 'SABINEWRENS3', 'LUKESKYWALKER', 'GRANDMASTERYODA', 'AAYLASECURA', 'QUIGONJINN', 'LUMINARAUNDULI', 'ANAKINKNIGHT', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'TEEBO', 'PAPLOO' ] },
          5: { active: true, units: [ 'JYNERSO', 'CASSIANANDOR', 'BAZEMALBUS', 'CHIRRUTIMWE', 'K2SO', 'PAO', 'IMAGUNDI', 'JEDIKNIGHTCONSULAR', 'QUIGONJINN', 'OLDBENKENOBI', 'PLOKOON', 'CC2224', 'CT210408', 'CT5555', 'CLONESERGEANTPHASEI' ] },
          6: { active: true, units: [ 'JYNERSO', 'BODHIROOK', 'PAO', 'BISTAN', 'SCARIFREBEL', 'KITFISTO', 'BARRISSOFFEE', 'KANANJARRUSS3', 'EETHKOTH', 'AHSOKATANO', 'CHIEFNEBIT', 'DATHCHA', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'LUKESKYWALKER', 'OLDBENKENOBI', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'PRINCESSLEIA', 'GRANDMASTERYODA', 'MACEWINDU', 'LUMINARAUNDULI', 'IMAGUNDI', 'PLOKOON', 'CLONEWARSCHEWBACCA', 'CORUSCANTUNDERWORLDPOLICE', 'CLONESERGEANTPHASEI', 'ANAKINKNIGHT', 'AHSOKATANO' ] },
          2: { active: true, units: [ 'PRINCESSLEIA', 'LOBOT', 'FULCRUMAHSOKA', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'CHOPPERS3', 'EZRABRIDGERS3', 'FULCRUMAHSOKA', 'WEDGEANTILLES', 'ZEBS3', 'CC2224', 'CT210408', 'CT5555', 'CLONESERGEANTPHASEI', 'CT7567' ] },
          3: { active: true, units: [ 'HERASYNDULLAS3', 'KANANJARRUSS3', 'CHOPPERS3', 'EZRABRIDGERS3', 'SABINEWRENS3', 'KITFISTO', 'EETHKOTH', 'OLDBENKENOBI', 'QUIGONJINN', 'AHSOKATANO', 'CHIEFNEBIT', 'DATHCHA', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER' ] },
          4: { active: true, units: [ 'BODHIROOK', 'PAO', 'BISTAN', 'CASSIANANDOR', 'K2SO', 'IMAGUNDI', 'JEDIKNIGHTCONSULAR', 'EETHKOTH', 'OLDBENKENOBI', 'PLOKOON', 'FINN', 'POE', 'REY', 'RESISTANCETROOPER', 'RESISTANCEPILOT' ] },
          5: { active: true, units: [ 'JYNERSO', 'CASSIANANDOR', 'BAZEMALBUS', 'CHIRRUTIMWE', 'K2SO', 'MACEWINDU', 'ANAKINKNIGHT', 'JEDIKNIGHTGUARDIAN', 'AAYLASECURA', 'BARRISSOFFEE', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'TEEBO', 'PAPLOO' ] },
          6: { active: true, units: [ 'CHOPPERS3', 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'ZEBS3', 'LUKESKYWALKER', 'GRANDMASTERYODA', 'AAYLASECURA', 'QUIGONJINN', 'KITFISTO', 'ANAKINKNIGHT', 'TEEBO', 'EWOKSCOUT', 'PAPLOO', 'LOGRAY', 'EWOKELDER' ] }
        }
      }
    }
  },
  4: {
    stars: 5,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'TIEREAPER', 'TIEADVANCED', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX' ] },
          2: { active: true, units: [ 'SITHINFILTRATOR', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'GEONOSIANSTARFIGHTER3', 'SLAVE1', 'XWINGRED3', 'MILLENNIUMFALCONEP7', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST' ] },
          3: { active: true, units: [ 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2' ] },
          4: { active: true, units: [ 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'BLADEOFDORIN', 'GHOST', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX' ] },
          5: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'HOUNDSTOOTH', 'PHANTOM2', 'COMMANDSHUTTLE', 'GAUNTLETSTARFIGHTER', 'UWINGROGUEONE', 'ARC170CLONESERGEANT', 'ARC170REX', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'QUIGONJINN', 'MACEWINDU', 'PLOKOON', 'CLONEWARSCHEWBACCA', 'BARRISSOFFEE', 'STORMTROOPERHAN', 'LUKESKYWALKER', 'ENFYSNEST', 'PRINCESSLEIA', 'OLDBENKENOBI', 'ADMIRALACKBAR', 'BIGGSDARKLIGHTER', 'STORMTROOPERHAN', 'ZEBS3', 'PRINCESSLEIA' ] },
          2: { active: true, units: [ 'SABINEWRENS3', 'OLDBENKENOBI', 'CHIRRUTIMWE', 'BAZEMALBUS', 'LUKESKYWALKER', 'JEDIKNIGHTGUARDIAN', 'CLONESERGEANTPHASEI', 'AHSOKATANO', 'CT5555', 'MACEWINDU', 'CT7567', 'CT210408', 'CC2224', 'KANANJARRUSS3', 'CHIEFNEBIT' ] },
          3: { active: true, units: [ 'ADMINISTRATORLANDO', 'CHOPPERS3', 'ADMIRALACKBAR', 'BIGGSDARKLIGHTER', 'LUKESKYWALKER', 'ANAKINKNIGHT', 'CT210408', 'JEDIKNIGHTCONSULAR', 'LUMINARAUNDULI', 'CC2224', 'REY', 'JAWA', 'JAWAENGINEER', 'JAWASCAVENGER', 'WICKET' ] },
          4: { active: true, units: [ 'EZRABRIDGERS3', 'BISTAN', 'BODHIROOK', 'WEDGEANTILLES', 'HERASYNDULLAS3', 'SMUGGLERCHEWBACCA', 'SMUGGLERHAN', 'POE', 'RESISTANCEPILOT', 'FINN', 'CASSIANANDOR', 'K2SO', 'PAO', 'BISTAN', 'CHOPPERS3' ] },
          5: { active: true, units: [ 'CHIEFCHIRPA', 'EWOKELDER', 'TEEBO', 'EWOKSCOUT', 'WICKET', 'CASSIANANDOR', 'K2SO', 'CHIRRUTIMWE', 'BAZEMALBUS', 'JYNERSO', 'ADMIRALACKBAR', 'OLDBENKENOBI', 'JAWAENGINEER', 'PRINCESSLEIA', 'WEDGEANTILLES' ] },
          6: { active: true, units: [ 'REY', 'RESISTANCEPILOT', 'POE', 'QUIGONJINN', 'L3_37', 'YOUNGHAN', 'QIRA', 'YOUNGCHEWBACCA', 'ENFYSNEST', 'YOUNGLANDO', 'JYNERSO', 'SCARIFREBEL', 'WEDGEANTILLES', 'JAWASCAVENGER', 'HOTHHAN' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'AHSOKATANO', 'ANAKINKNIGHT', 'AAYLASECURA', 'CT5555', 'LUMINARAUNDULI', 'ADMINISTRATORLANDO', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'FULCRUMAHSOKA', 'LUKESKYWALKER', 'STORMTROOPERHAN', 'WEDGEANTILLES', 'BIGGSDARKLIGHTER', 'ADMINISTRATORLANDO', 'PRINCESSLEIA' ] },
          2: { active: true, units: [ 'HERASYNDULLAS3', 'STORMTROOPERHAN', 'PRINCESSLEIA', 'SCARIFREBEL', 'BIGGSDARKLIGHTER', 'ANAKINKNIGHT', 'CLONEWARSCHEWBACCA', 'QUIGONJINN', 'LUMINARAUNDULI', 'JEDIKNIGHTCONSULAR', 'REY', 'FINN', 'RESISTANCEPILOT', 'RESISTANCETROOPER', 'SMUGGLERCHEWBACCA' ] },
          3: { active: true, units: [ 'AHSOKATANO', 'ANAKINKNIGHT', 'QUIGONJINN', 'MACEWINDU', 'LUMINARAUNDULI', 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'PAPLOO', 'LOGRAY', 'BARRISSOFFEE', 'CLONESERGEANTPHASEI', 'AAYLASECURA', 'PLOKOON', 'JEDIKNIGHTCONSULAR' ] },
          4: { active: true, units: [ 'TEEBO', 'WICKET', 'EWOKSCOUT', 'LOGRAY', 'PAPLOO', 'SABINEWRENS3', 'KANANJARRUSS3', 'EZRABRIDGERS3', 'ZEBS3', 'OLDBENKENOBI', 'JEDIKNIGHTCONSULAR', 'BARRISSOFFEE', 'JEDIKNIGHTGUARDIAN', 'QUIGONJINN', 'CORUSCANTUNDERWORLDPOLICE' ] },
          5: { active: true, units: [ 'ADMINISTRATORLANDO', 'LUKESKYWALKER', 'BIGGSDARKLIGHTER', 'WEDGEANTILLES', 'UGNAUGHT', 'AHSOKATANO', 'ANAKINKNIGHT', 'CT7567', 'MACEWINDU', 'PLOKOON', 'SMUGGLERHAN', 'SMUGGLERCHEWBACCA', 'AMILYNHOLDO', 'RESISTANCETROOPER', 'POE' ] },
          6: { active: true, units: [ 'YOUNGHAN', 'YOUNGLANDO', 'YOUNGCHEWBACCA', 'QIRA', 'L3_37', 'ROSETICO', 'POE', 'RESISTANCEPILOT', 'REY', 'SMUGGLERHAN', 'CHIEFCHIRPA', 'LOGRAY', 'PAPLOO', 'EWOKELDER', 'TEEBO' ] }
        }
      }
    }
  },
  5: {
    stars: 6,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'GHOST', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'ARC170CLONESERGEANT', 'ARC170REX', 'PHANTOM2', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'GEONOSIANSTARFIGHTER2', 'TIEADVANCED', 'TIEFIGHTERFOSF' ] },
          2: { active: true, units: [ 'UWINGROGUEONE', 'GHOST', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'MILLENNIUMFALCON', 'GHOST', 'TIESILENCER', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN' ] },
          4: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'GHOST', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX' ] },
          5: { active: true, units: [ 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'SITHINFILTRATOR', 'SLAVE1', 'XWINGRED3', 'MILLENNIUMFALCONEP7', 'JEDISTARFIGHTERANAKIN', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'HOUNDSTOOTH', 'PHANTOM2', 'COMMANDSHUTTLE', 'GAUNTLETSTARFIGHTER', 'UWINGROGUEONE' ] },
          6: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'SITHFIGHTER', 'SITHBOMBER', 'EBONHAWK', 'XANADUBLOOD', 'IG2000', 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'QUIGONJINN', 'MACEWINDU', 'PLOKOON', 'GRANDMASTERYODA', 'BARRISSOFFEE', 'STORMTROOPERHAN', 'LUKESKYWALKER', 'R2D2_LEGENDARY', 'PRINCESSLEIA', 'OLDBENKENOBI', 'CT210408', 'CLONESERGEANTPHASEI', 'VISASMARR', 'PLOKOON', 'JEDIKNIGHTCONSULAR' ] },
          2: { active: true, units: [ 'AHSOKATANO', 'ANAKINKNIGHT', 'GRANDMASTERYODA', 'MACEWINDU', 'LUMINARAUNDULI', 'AHSOKATANO', 'ANAKINKNIGHT', 'CT7567', 'MACEWINDU', 'PLOKOON', 'ROSETICO', 'POE', 'BB8', 'REY', 'SMUGGLERHAN' ] },
          3: { active: true, units: [ 'ADMINISTRATORLANDO', 'HANSOLO', 'BIGGSDARKLIGHTER', 'WEDGEANTILLES', 'UGNAUGHT', 'JEDIKNIGHTCONSULAR', 'BARRISSOFFEE', 'JEDIKNIGHTGUARDIAN', 'QUIGONJINN', 'CORUSCANTUNDERWORLDPOLICE', 'ADMIRALACKBAR', 'FULCRUMAHSOKA', 'BAZEMALBUS', 'R2D2_LEGENDARY', 'PRINCESSLEIA' ] },
          4: { active: true, units: [ 'ADMINISTRATORLANDO', 'UGNAUGHT', 'ADMIRALACKBAR', 'BIGGSDARKLIGHTER', 'LUKESKYWALKER', 'GENERALKENOBI', 'CT210408', 'CT5555', 'MACEWINDU', 'CC2224', 'CHIEFNEBIT', 'JAWA', 'JAWAENGINEER', 'LOBOT', 'DATHCHA' ] },
          5: { active: true, units: [ 'CHIEFCHIRPA', 'EWOKELDER', 'EWOKSCOUT', 'PAPLOO', 'LOGRAY', 'TEEBO', 'WICKET', 'EWOKSCOUT', 'CHIEFNEBIT', 'JAWASCAVENGER', 'SMUGGLERHAN', 'SMUGGLERCHEWBACCA', 'AMILYNHOLDO', 'R2D2_LEGENDARY', 'L3_37' ] },
          6: { active: true, units: [ 'YOUNGHAN', 'YOUNGLANDO', 'YOUNGCHEWBACCA', 'QIRA', 'L3_37', 'QIRA', 'YOUNGHAN', 'YOUNGCHEWBACCA', 'HERMITYODA', 'OLDBENKENOBI', 'CHIEFCHIRPA', 'LOGRAY', 'PAPLOO', 'EWOKELDER', 'TEEBO' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'AHSOKATANO', 'ANAKINKNIGHT', 'GRANDMASTERYODA', 'CT5555', 'LUMINARAUNDULI', 'ADMINISTRATORLANDO', 'STORMTROOPERHAN', 'ADMIRALACKBAR', 'FULCRUMAHSOKA', 'LUKESKYWALKER', 'REY', 'FINN', 'RESISTANCEPILOT', 'RESISTANCETROOPER', 'SMUGGLERCHEWBACCA' ] },
          2: { active: true, units: [ 'MISSIONVAO', 'ZAALBAR', 'T3_M4', 'JOLEEBINDO', 'BASTILASHAN', 'AHSOKATANO', 'CLONESERGEANTPHASEI', 'QUIGONJINN', 'LUMINARAUNDULI', 'JEDIKNIGHTCONSULAR', 'ADMIRALACKBAR', 'OLDBENKENOBI', 'HERMITYODA', 'PRINCESSLEIA', 'SMUGGLERHAN' ] },
          3: { active: true, units: [ 'CHIEFCHIRPA', 'EWOKELDER', 'TEEBO', 'EWOKSCOUT', 'WICKET', 'JEDIKNIGHTGUARDIAN', 'CLONESERGEANTPHASEI', 'AHSOKATANO', 'CT5555', 'MACEWINDU', 'CHEWBACCALEGENDARY', 'PAO', 'BIGGSDARKLIGHTER', 'ADMINISTRATORLANDO', 'HERMITYODA' ] },
          4: { active: true, units: [ 'CASSIANANDOR', 'BISTAN', 'BODHIROOK', 'K2SO', 'BAZEMALBUS', 'SMUGGLERCHEWBACCA', 'SMUGGLERHAN', 'POE', 'BB8', 'FINN', 'CASSIANANDOR', 'K2SO', 'PAO', 'BISTAN', 'CHIEFNEBIT' ] },
          5: { active: true, units: [ 'CASSIANANDOR', 'K2SO', 'CHIRRUTIMWE', 'BAZEMALBUS', 'JYNERSO', 'CASSIANANDOR', 'K2SO', 'C3POLEGENDARY', 'BAZEMALBUS', 'JYNERSO', 'HOTHHAN', 'KITFISTO', 'HOTHREBELSOLDIER', 'OLDBENKENOBI', 'HERMITYODA' ] },
          6: { active: true, units: [ 'JAWAENGINEER', 'ADMIRALACKBAR', 'PRINCESSLEIA', 'SCARIFREBEL', 'HANSOLO', 'YOUNGHAN', 'QIRA', 'YOUNGCHEWBACCA', 'ENFYSNEST', 'CORUSCANTUNDERWORLDPOLICE', 'SMUGGLERCHEWBACCA', 'SCARIFREBEL', 'WEDGEANTILLES', 'HOTHREBELSOLDIER', 'HOTHHAN' ] }
        }
      }
    }
  },
  6: {
    stars: 7,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'EMPERORSSHUTTLE', 'SLAVE1', 'TIEADVANCED' ] },
          2: { active: true, units: [ 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERANAKIN', 'XWINGRED3', 'UWINGSCARIF', 'ARC170CLONESERGEANT', 'MILLENNIUMFALCON', 'GHOST', 'HOUNDSTOOTH', 'EBONHAWK', 'SLAVE1', 'UMBARANSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR' ] },
          3: { active: true, units: [ 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'SITHINFILTRATOR', 'SLAVE1', 'XWINGRED2', 'XWINGBLACKONE', 'MILLENNIUMFALCON', 'GHOST', 'TIESILENCER', 'MILLENNIUMFALCON', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCONPRISTINE', 'PHANTOM2', 'GHOST' ] },
          4: { active: true, units: [ 'TIEFIGHTERIMPERIAL', 'TIESILENCER', 'TIEFIGHTERFIRSTORDER', 'TIEADVANCED', 'TIEREAPER', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'GHOST', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCON', 'EBONHAWK', 'MILLENNIUMFALCONPRISTINE' ] },
          5: { active: true, units: [ 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER', 'GEONOSIANSTARFIGHTER3', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'SITHBOMBER', 'XANADUBLOOD', 'IG2000', 'SITHFIGHTER', 'SITHINFILTRATOR' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERFOSF', 'COMMANDSHUTTLE', 'TIESILENCER', 'MILLENNIUMFALCONEP7' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'QUIGONJINN', 'AAYLASECURA', 'AHSOKATANO', 'GRANDMASTERYODA', 'BARRISSOFFEE', 'STORMTROOPERHAN', 'LUKESKYWALKER', 'C3POLEGENDARY', 'PRINCESSLEIA', 'OLDBENKENOBI', 'ADMIRALACKBAR', 'FULCRUMAHSOKA', 'HERMITYODA', 'SABINEWRENS3', 'COMMANDERLUKESKYWALKER' ] },
          2: { active: true, units: [ 'ADMINISTRATORLANDO', 'HANSOLO', 'SABINEWRENS3', 'WEDGEANTILLES', 'HERMITYODA', 'CORUSCANTUNDERWORLDPOLICE', 'CC2224', 'BARRISSOFFEE', 'MACEWINDU', 'QUIGONJINN', 'SMUGGLERHAN', 'POE', 'AMILYNHOLDO', 'REYJEDITRAINING', 'FINN' ] },
          3: { active: true, units: [ 'CC2224', 'ANAKINKNIGHT', 'AAYLASECURA', 'MACEWINDU', 'LUMINARAUNDULI', 'C3POLEGENDARY', 'LOGRAY', 'PAPLOO', 'WICKET', 'HERMITYODA', 'BARRISSOFFEE', 'ANAKINKNIGHT', 'VISASMARR', 'CT7567', 'CORUSCANTUNDERWORLDPOLICE' ] },
          4: { active: true, units: [ 'ADMINISTRATORLANDO', 'WEDGEANTILLES', 'KITFISTO', 'KANANJARRUSS3', 'LUKESKYWALKER', 'GENERALKENOBI', 'QUIGONJINN', 'VISASMARR', 'GRANDMASTERYODA', 'BARRISSOFFEE', 'CHIEFNEBIT', 'JAWA', 'DATHCHA', 'JAWASCAVENGER', 'EZRABRIDGERS3' ] },
          5: { active: true, units: [ 'JEDIKNIGHTREVAN', 'ZAALBAR', 'T3_M4', 'JOLEEBINDO', 'BASTILASHAN', 'YOUNGHAN', 'YOUNGLANDO', 'PLOKOON', 'L3_37', 'REYJEDITRAINING', 'ADMINISTRATORLANDO', 'KANANJARRUSS3', 'HOTHREBELSCOUT', 'HOTHREBELSOLDIER', 'HOTHHAN' ] },
          6: { active: true, units: [ 'YOUNGHAN', 'YOUNGLANDO', 'ENFYSNEST', 'R2D2_LEGENDARY', 'L3_37', 'ROSETICO', 'POE', 'BB8', 'REY', 'AMILYNHOLDO', 'KANANJARRUSS3', 'CHEWBACCALEGENDARY', 'EWOKSCOUT', 'EZRABRIDGERS3', 'LOGRAY' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'AHSOKATANO', 'ANAKINKNIGHT', 'GRANDMASTERYODA', 'QUIGONJINN', 'IMAGUNDI', 'L3_37', 'SMUGGLERHAN', 'POE', 'REYJEDITRAINING', 'HERMITYODA', 'ZEBS3', 'WICKET', 'CHEWBACCALEGENDARY', 'SMUGGLERCHEWBACCA', 'ZAALBAR' ] },
          2: { active: true, units: [ 'SABINEWRENS3', 'EZRABRIDGERS3', 'TEEBO', 'CHEWBACCALEGENDARY', 'HERMITYODA', 'EETHKOTH', 'GENERALKENOBI', 'JEDIKNIGHTGUARDIAN', 'IMAGUNDI', 'CORUSCANTUNDERWORLDPOLICE', 'ADMIRALACKBAR', 'LOGRAY', 'STORMTROOPERHAN', 'PRINCESSLEIA', 'WEDGEANTILLES' ] },
          3: { active: true, units: [ 'ADMINISTRATORLANDO', 'STORMTROOPERHAN', 'UGNAUGHT', 'KITFISTO', 'PLOKOON', 'HERMITYODA', 'HOTHHAN', 'FULCRUMAHSOKA', 'COMMANDERLUKESKYWALKER', 'EZRABRIDGERS3', 'HOTHHAN', 'HOTHREBELSCOUT', 'HOTHREBELSOLDIER', 'FULCRUMAHSOKA', 'COMMANDERLUKESKYWALKER' ] },
          4: { active: true, units: [ 'CHOPPERS3', 'HERASYNDULLAS3', 'ZEBS3', 'KANANJARRUSS3', 'LOBOT', 'CT210408', 'CT7567', 'GRANDMASTERYODA', 'EETHKOTH', 'LUMINARAUNDULI', 'STORMTROOPERHAN', 'WEDGEANTILLES', 'LOBOT', 'ADMINISTRATORLANDO', 'HERMITYODA' ] },
          5: { active: true, units: [ 'ADMINISTRATORLANDO', 'ENFYSNEST', 'PRINCESSLEIA', 'BIGGSDARKLIGHTER', 'HANSOLO', 'T3_M4', 'BASTILASHAN', 'JEDIKNIGHTREVAN', 'JUHANI', 'ZAALBAR', 'REY', 'FINN', 'C3POLEGENDARY', 'BB8', 'POE' ] },
          6: { active: true, units: [ 'POE', 'REY', 'HERMITYODA', 'R2D2_LEGENDARY', 'ROSETICO', 'CHOPPERS3', 'UGNAUGHT', 'JUHANI', 'KANANJARRUSS3', 'CARTHONASI', 'JOLEEBINDO', 'JUHANI', 'CARTHONASI', 'T3_M4', 'MISSIONVAO' ] }
        }
      }
    }
  }
}

export const GeonosisDS = {
  1: {
    stars: 6,
    territories: {
      top: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'DAKA', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'TALIA', 'BASTILASHANDARK', 'VEERS', 'IG86SENTINELDROID', 'IG88', 'DARTHTRAYA', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN' ] },
          2: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'VEERS', 'SITHTROOPER', 'HK47', 'BOSSK', 'IG86SENTINELDROID', 'WAMPA', 'RANGETROOPER', 'JANGOFETT', 'RANGETROOPER', 'DARTHTRAYA', 'BOSSK', 'MOTHERTALZIN' ] },
          3: { active: true, units: [ 'TALIA', 'MOTHERTALZIN', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE', 'BASTILASHANDARK', 'JANGOFETT', 'IG86SENTINELDROID', 'BOSSK', 'VEERS', 'GARSAXON', 'DEATHTROOPER', 'ROYALGUARD', 'DIRECTORKRENNIC', 'FIRSTORDERTIEPILOT' ] },
          4: { active: true, units: [ 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'MAUL', 'SAVAGEOPRESS', 'HK47', 'VEERS', 'IG86SENTINELDROID', 'WAMPA', 'BOSSK', 'TALIA', 'MOTHERTALZIN', 'DAKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERINITIATE' ] },
          5: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'EMPERORPALPATINE', 'ROYALGUARD', 'GARSAXON', 'FIRSTORDERTIEPILOT', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'SITHASSASSIN', 'SITHTROOPER', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'VEERS', 'SITHTROOPER' ] },
          6: { active: true, units: [ 'JANGOFETT', 'VEERS', 'WAMPA', 'BOSSK', 'MOTHERTALZIN', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'DARTHREVAN', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'ASAJVENTRESS', 'URORRURRR' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GARSAXON', 'IMPERIALSUPERCOMMANDO', 'BASTILASHANDARK', 'DIRECTORKRENNIC', 'FIRSTORDERTIEPILOT', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHTROOPER', 'BASTILASHANDARK', 'SAVAGEOPRESS', 'URORRURRR', 'TUSKENSHAMAN', 'MOTHERTALZIN', 'HUMANTHUG', 'GRANDMOFFTARKIN' ] },
          2: { active: true, units: [ 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'VEERS', 'SITHTROOPER', 'HK47', 'JANGOFETT', 'IG86SENTINELDROID', 'DARTHTRAYA', 'RANGETROOPER', 'BOSSK', 'BASTILASHANDARK', 'IG86SENTINELDROID', 'JANGOFETT', 'RANGETROOPER' ] },
          3: { active: true, units: [ 'DAKA', 'VEERS', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERINITIATE', 'TALIA', 'DARTHTRAYA', 'JANGOFETT', 'BASTILASHANDARK', 'BOSSK', 'WAMPA', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'MOTHERTALZIN' ] },
          4: { active: true, units: [ 'TALIA', 'MOTHERTALZIN', 'DAKA', 'SAVAGEOPRESS', 'NIGHTSISTERINITIATE', 'WAMPA', 'DIRECTORKRENNIC', 'IG86SENTINELDROID', 'BOSSK', 'VEERS', 'GRANDMOFFTARKIN', 'FIRSTORDERTIEPILOT', 'ROYALGUARD', 'DIRECTORKRENNIC', 'BASTILASHANDARK' ] },
          5: { active: true, units: [ 'EMPERORPALPATINE', 'VEERS', 'DARTHNIHILUS', 'MAUL', 'SITHTROOPER', 'BASTILASHANDARK', 'IMPERIALSUPERCOMMANDO', 'MOTHERTALZIN', 'DIRECTORKRENNIC', 'FIRSTORDERTIEPILOT', 'HK47', 'DARTHREVAN', 'IG86SENTINELDROID', 'WAMPA', 'GARSAXON' ] },
          6: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'FIRSTORDERTIEPILOT', 'ROYALGUARD', 'BASTILASHANDARK', 'GRANDMOFFTARKIN', 'PHASMA', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'FIRSTORDEROFFICERMALE', 'KYLOREN', 'DARTHSIDIOUS', 'MAUL', 'SAVAGEOPRESS', 'VEERS', 'SITHTROOPER' ] }
        }
      }
    }
  },
  2: {
    stars: 6,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'EBONHAWK', 'TIEFIGHTERIMPERIAL', 'SLAVE1', 'HOUNDSTOOTH', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'TIEREAPER', 'TIEADVANCED', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'EMPERORSSHUTTLE' ] },
          2: { active: true, units: [ 'SITHINFILTRATOR', 'TIEFIGHTERIMPERIAL', 'EMPERORSSHUTTLE', 'GEONOSIANSTARFIGHTER3', 'SLAVE1', 'XWINGRED3', 'HOUNDSTOOTH', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'SLAVE1', 'UWINGROGUEONE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'EBONHAWK' ] },
          3: { active: true, units: [ 'EBONHAWK', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'PHANTOM2', 'TIEFIGHTERIMPERIAL', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX', 'ARC170CLONESERGEANT', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'XWINGRED2' ] },
          4: { active: true, units: [ 'UWINGROGUEONE', 'EBONHAWK', 'GEONOSIANSTARFIGHTER3', 'XWINGBLACKONE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'BLADEOFDORIN', 'HOUNDSTOOTH', 'TIESILENCER', 'JEDISTARFIGHTERAHSOKATANO', 'EMPERORSSHUTTLE', 'BLADEOFDORIN', 'ARC170CLONESERGEANT', 'ARC170REX' ] },
          5: { active: true, units: [ 'EBONHAWK', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'GHOST', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'SLAVE1', 'PHANTOM2', 'GAUNTLETSTARFIGHTER', 'ARC170REX', 'UMBARANSTARFIGHTER' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'SITHBOMBER', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'HOUNDSTOOTH', 'PHANTOM2', 'COMMANDSHUTTLE', 'EMPERORSSHUTTLE', 'UWINGROGUEONE', 'ARC170CLONESERGEANT', 'ARC170REX', 'EBONHAWK', 'BLADEOFDORIN', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRIEVOUS', 'MAUL', 'CADBANE', 'ZAMWESELL', 'DARTHREVAN', 'B1BATTLEDROIDV2', 'STORMTROOPER', 'GRIEVOUS', 'GRIEVOUS', 'IMPERIALPROBEDROID', 'MOTHERTALZIN', 'BOSSK', 'MAUL', 'JANGOFETT', 'DAKA' ] },
          2: { active: true, units: [ 'CADBANE', 'DROIDEKA', 'DARTHSIDIOUS', 'DARTHREVAN', 'GRIEVOUS', 'GRANDMOFFTARKIN', 'SHORETROOPER', 'STORMTROOPER', 'IMPERIALPROBEDROID', 'DROIDEKA', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERZOMBIE', 'NIGHTSISTERSPIRIT', 'BOSSK', 'DAKA' ] },
          3: { active: true, units: [ 'DARTHSION', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHMARAUDER', 'SITHTROOPER', 'DROIDEKA', 'B1BATTLEDROIDV2', 'NUTEGUNRAY', 'DARTHTRAYA', 'GRIEVOUS', 'DARTHREVAN', 'JANGOFETT', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'FIRSTORDERTROOPER' ] },
          4: { active: true, units: [ 'CADBANE', 'JANGOFETT', 'MOTHERTALZIN', 'BOSSK', 'EMBO', 'PHASMA', 'KYLOREN', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'BASTILASHANDARK', 'COLONELSTARCK', 'RANGETROOPER', 'STORMTROOPER', 'DEATHTROOPER', 'GRIEVOUS' ] },
          5: { active: true, units: [ 'BASTILASHANDARK', 'HUMANTHUG', 'AURRA_SING', 'BOSSK', 'IMPERIALPROBEDROID', 'JANGOFETT', 'ZAMWESELL', 'BASTILASHANDARK', 'BOBAFETT', 'GREEDO', 'JANGOFETT', 'DARTHREVAN', 'GRIEVOUS', 'DROIDEKA', 'B1BATTLEDROIDV2' ] },
          6: { active: true, units: [ 'GRIEVOUS', 'DARTHNIHILUS', 'SITHMARAUDER', 'MOTHERTALZIN', 'HK47', 'FIRSTORDEREXECUTIONER', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDERTIEPILOT', 'DARTHTRAYA', 'NUTEGUNRAY', 'DARTHREVAN', 'JANGOFETT', 'DROIDEKA', 'B1BATTLEDROIDV2' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRIEVOUS', 'DEATHTROOPER', 'STORMTROOPER', 'FIRSTORDERTIEPILOT', 'VADER', 'MOTHERTALZIN', 'DARTHREVAN', 'DARTHTRAYA', 'DAKA', 'NIGHTSISTERACOLYTE', 'BASTILASHANDARK', 'NIGHTSISTERSPIRIT', 'BOSSK', 'MOTHERTALZIN', 'DARTHTRAYA' ] },
          2: { active: true, units: [ 'IMPERIALSUPERCOMMANDO', 'DARTHREVAN', 'JANGOFETT', 'GREEDO', 'BOSSK', 'FIRSTORDERTIEPILOT', 'VADER', 'BASTILASHANDARK', 'SHORETROOPER', 'IMPERIALPROBEDROID', 'NIGHTSISTERINITIATE', 'NIGHTSISTERSPIRIT', 'MOTHERTALZIN', 'GRIEVOUS', 'SAVAGEOPRESS' ] },
          3: { active: true, units: [ 'FIRSTORDEROFFICERMALE', 'GRIEVOUS', 'FIRSTORDERTROOPER', 'KYLORENUNMASKED', 'HUMANTHUG', 'FIRSTORDERTROOPER', 'KYLOREN', 'KYLORENUNMASKED', 'DARTHSIDIOUS', 'DARTHREVAN', 'JANGOFETT', 'BOSSK', 'HK47', 'BASTILASHANDARK', 'DENGAR' ] },
          4: { active: true, units: [ 'GRIEVOUS', 'BASTILASHANDARK', 'DARTHSIDIOUS', 'DARTHTRAYA', 'JANGOFETT', 'MOTHERTALZIN', 'MAUL', 'KYLORENUNMASKED', 'GRIEVOUS', 'BOSSK', 'CADBANE', 'IG86SENTINELDROID', 'MAGNAGUARD', 'DARTHREVAN', 'B2SUPERBATTLEDROID' ] },
          5: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'MOTHERTALZIN', 'DARTHSION', 'HK47', 'KYLORENUNMASKED', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'DARTHREVAN', 'HUMANTHUG', 'DARTHTRAYA', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRIEVOUS' ] },
          6: { active: true, units: [ 'DARTHREVAN', 'GARSAXON', 'JANGOFETT', 'STORMTROOPER', 'RANGETROOPER', 'DARTHSIDIOUS', 'DARTHTRAYA', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'URORRURRR', 'GRIEVOUS', 'DROIDEKA', 'B1BATTLEDROIDV2', 'BASTILASHANDARK', 'JANGOFETT' ] }
        }
      }
    }
  },
  3: {
    stars: 7,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'HOUNDSTOOTH', 'GAUNTLETSTARFIGHTER', 'XWINGRED2', 'EBONHAWK', 'TIEFIGHTERIMPERIAL', 'ARC170CLONESERGEANT', 'ARC170REX', 'EBONHAWK', 'BLADEOFDORIN', 'JEDISTARFIGHTERANAKIN', 'TIEFIGHTERFIRSTORDER', 'TIEFIGHTERIMPERIAL', 'MILLENNIUMFALCON', 'TIEADVANCED', 'EMPERORSSHUTTLE' ] },
          2: { active: true, units: [ 'UWINGROGUEONE', 'HOUNDSTOOTH', 'MILLENNIUMFALCON', 'EMPERORSSHUTTLE', 'SITHINFILTRATOR', 'XWINGRED2', 'XWINGBLACKONE', 'MILLENNIUMFALCON', 'HOUNDSTOOTH', 'EMPERORSSHUTTLE', 'JEDISTARFIGHTERANAKIN', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'HOUNDSTOOTH' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'EBONHAWK', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'ARC170CLONESERGEANT', 'ARC170REX', 'XWINGBLACKONE', 'XWINGRED3', 'EBONHAWK', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'MILLENNIUMFALCON', 'ARC170CLONESERGEANT', 'BLADEOFDORIN' ] },
          4: { active: true, units: [ 'MILLENNIUMFALCONPRISTINE', 'XWINGRED3', 'TIEFIGHTERIMPERIAL', 'EMPERORSSHUTTLE', 'HOUNDSTOOTH', 'HOUNDSTOOTH', 'IG2000', 'MILLENNIUMFALCONEP7', 'SLAVE1', 'XANADUBLOOD', 'MILLENNIUMFALCON', 'JEDISTARFIGHTERANAKIN', 'EBONHAWK', 'JEDISTARFIGHTERCONSULAR', 'ARC170REX' ] },
          5: { active: true, units: [ 'MILLENNIUMFALCON', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'TIESILENCER', 'SLAVE1', 'XWINGRED3', 'MILLENNIUMFALCONEP7', 'JEDISTARFIGHTERANAKIN', 'MILLENNIUMFALCON', 'EMPERORSSHUTTLE', 'HOUNDSTOOTH', 'JEDISTARFIGHTERANAKIN', 'COMMANDSHUTTLE', 'GAUNTLETSTARFIGHTER', 'EMPERORSSHUTTLE' ] },
          6: { active: true, units: [ 'EBONHAWK', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'HOUNDSTOOTH', 'SITHFIGHTER', 'SITHBOMBER', 'EBONHAWK', 'XANADUBLOOD', 'IG2000', 'SLAVE1', 'JEDISTARFIGHTERANAKIN', 'GAUNTLETSTARFIGHTER', 'EBONHAWK', 'UMBARANSTARFIGHTER' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'PHASMA', 'DARTHMALAK', 'BOSSK', 'FIRSTORDEREXECUTIONER', 'FIRSTORDERSPECIALFORCESPILOT', 'MOTHERTALZIN', 'TALIA', 'DARTHREVAN', 'SAVAGEOPRESS', 'DAKA', 'EMPERORPALPATINE', 'FIRSTORDERTIEPILOT', 'AURRA_SING', 'DIRECTORKRENNIC', 'DEATHTROOPER' ] },
          2: { active: true, units: [ 'ASAJVENTRESS', 'RANGETROOPER', 'BASTILASHANDARK', 'DARTHREVAN', 'DARTHMALAK', 'MOTHERTALZIN', 'EMPERORPALPATINE', 'JANGOFETT', 'GRANDADMIRALTHRAWN', 'IMPERIALPROBEDROID', 'NIGHTSISTERINITIATE', 'MOTHERTALZIN', 'BOSSK', 'SAVAGEOPRESS', 'DAKA' ] },
          3: { active: true, units: [ 'BOSSK', 'EMPERORPALPATINE', 'GRANDADMIRALTHRAWN', 'RANGETROOPER', 'DARTHREVAN', 'MOTHERTALZIN', 'DEATHTROOPER', 'SHORETROOPER', 'STORMTROOPER', 'GRANDMOFFTARKIN', 'FIRSTORDERTIEPILOT', 'WAMPA', 'COLONELSTARCK', 'SHORETROOPER', 'IMPERIALPROBEDROID' ] },
          4: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'HK47', 'BOSSK', 'DARTHREVAN', 'JANGOFETT', 'SHORETROOPER', 'GRANDADMIRALTHRAWN', 'WAMPA', 'ROYALGUARD', 'DARTHMALAK', 'DAKA', 'NIGHTSISTERSPIRIT', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE' ] },
          5: { active: true, units: [ 'DARTHTRAYA', 'JANGOFETT', 'SITHMARAUDER', 'SITHTROOPER', 'DARTHSION', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'DARTHREVAN', 'BOSSK', 'FIRSTORDERTROOPER', 'VEERS', 'DARTHMALAK', 'BOSSK', 'WAMPA', 'SNOWTROOPER' ] },
          6: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'SITHMARAUDER', 'SITHTROOPER', 'MOTHERTALZIN', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'DARTHREVAN', 'FIRSTORDEREXECUTIONER', 'FIRSTORDEROFFICERMALE', 'EMBO', 'JANGOFETT', 'DARTHMALAK', 'DARTHREVAN', 'ASAJVENTRESS' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRANDMOFFTARKIN', 'DARTHREVAN', 'EMPERORPALPATINE', 'GRANDADMIRALTHRAWN', 'WAMPA', 'VEERS', 'SNOWTROOPER', 'DARTHREVAN', 'EMPERORPALPATINE', 'GRANDMOFFTARKIN', 'VEERS', 'KYLORENUNMASKED', 'SNOWTROOPER', 'FIRSTORDERTIEPILOT', 'IMPERIALSUPERCOMMANDO' ] },
          2: { active: true, units: [ 'GRANDMOFFTARKIN', 'EMPERORPALPATINE', 'MAGMATROOPER', 'BOSSK', 'RANGETROOPER', 'PHASMA', 'FIRSTORDEROFFICERMALE', 'DARTHREVAN', 'FIRSTORDERTROOPER', 'IG86SENTINELDROID', 'BOSSK', 'JANGOFETT', 'AURRA_SING', 'EMBO', 'DENGAR' ] },
          3: { active: true, units: [ 'TALIA', 'MOTHERTALZIN', 'ASAJVENTRESS', 'DAKA', 'JANGOFETT', 'TUSKENRAIDER', 'STORMTROOPER', 'BOSSK', 'SNOWTROOPER', 'MAGMATROOPER', 'DARTHSION', 'DARTHTRAYA', 'DARTHNIHILUS', 'SITHASSASSIN', 'SITHMARAUDER' ] },
          4: { active: true, units: [ 'EMBO', 'AURRA_SING', 'DARTHREVAN', 'NUTEGUNRAY', 'SHORETROOPER', 'VEERS', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERTROOPER', 'FIRSTORDERTIEPILOT', 'KYLORENUNMASKED', 'WAMPA', 'DARTHMALAK', 'TUSKENRAIDER', 'TUSKENSHAMAN', 'GRANDADMIRALTHRAWN' ] },
          5: { active: true, units: [ 'DARTHMALAK', 'AURRA_SING', 'JANGOFETT', 'CADBANE', 'BOSSK', 'NIGHTSISTERACOLYTE', 'NIGHTSISTERZOMBIE', 'BOSSK', 'GRANDADMIRALTHRAWN', 'RANGETROOPER', 'TUSKENRAIDER', 'RANGETROOPER', 'URORRURRR', 'FIRSTORDERTIEPILOT', 'DARTHREVAN' ] },
          6: { active: true, units: [ 'TUSKENSHAMAN', 'URORRURRR', 'BOSSK', 'TUSKENRAIDER', 'HUMANTHUG', 'SITHMARAUDER', 'DARTHREVAN', 'URORRURRR', 'BOSSK', 'SHORETROOPER', 'GRANDADMIRALTHRAWN', 'IG86SENTINELDROID', 'DARTHMALAK', 'DARTHREVAN', 'IG88' ] }
        }
      }
    }
  },
  4: {
    stars: 7,
    territories: {
      top: {
        unitType: UnitType.SHIP,
        platoons: {
          1: { active: true, units: [ 'EMPERORSSHUTTLE', 'UWINGSCARIF', 'XWINGRED2', 'XWINGRED3', 'HOUNDSTOOTH', 'JEDISTARFIGHTERAHSOKATANO', 'EMPERORSSHUTTLE', 'BLADEOFDORIN', 'JEDISTARFIGHTERCONSULAR', 'HOUNDSTOOTH', 'TIEREAPER', 'TIEFIGHTERIMPERIAL', 'EMPERORSSHUTTLE', 'EBONHAWK', 'TIEADVANCED' ] },
          2: { active: true, units: [ 'EBONHAWK', 'JEDISTARFIGHTERANAKIN', 'XWINGRED3', 'HOUNDSTOOTH', 'ARC170CLONESERGEANT', 'MILLENNIUMFALCON', 'JEDISTARFIGHTERANAKIN', 'HOUNDSTOOTH', 'EBONHAWK', 'SLAVE1', 'UMBARANSTARFIGHTER', 'EMPERORSSHUTTLE', 'EBONHAWK', 'JEDISTARFIGHTERAHSOKATANO', 'HOUNDSTOOTH' ] },
          3: { active: true, units: [ 'HOUNDSTOOTH', 'TIEFIGHTERIMPERIAL', 'TIEADVANCED', 'TIESILENCER', 'SLAVE1', 'XWINGRED2', 'HOUNDSTOOTH', 'MILLENNIUMFALCON', 'JEDISTARFIGHTERANAKIN', 'TIESILENCER', 'MILLENNIUMFALCON', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCONPRISTINE', 'JEDISTARFIGHTERANAKIN', 'HOUNDSTOOTH' ] },
          4: { active: true, units: [ 'EMPERORSSHUTTLE', 'TIESILENCER', 'TIEFIGHTERFIRSTORDER', 'HOUNDSTOOTH', 'TIEREAPER', 'JEDISTARFIGHTERAHSOKATANO', 'JEDISTARFIGHTERCONSULAR', 'EBONHAWK', 'EMPERORSSHUTTLE', 'BLADEOFDORIN', 'HOUNDSTOOTH', 'MILLENNIUMFALCONEP7', 'MILLENNIUMFALCON', 'EBONHAWK', 'MILLENNIUMFALCONPRISTINE' ] },
          5: { active: true, units: [ 'SLAVE1', 'JEDISTARFIGHTERANAKIN', 'GAUNTLETSTARFIGHTER', 'HOUNDSTOOTH', 'UMBARANSTARFIGHTER', 'GEONOSIANSTARFIGHTER3', 'GEONOSIANSTARFIGHTER2', 'GEONOSIANSTARFIGHTER1', 'HOUNDSTOOTH', 'EBONHAWK', 'SITHBOMBER', 'XANADUBLOOD', 'IG2000', 'SITHFIGHTER', 'SITHINFILTRATOR' ] },
          6: { active: true, units: [ 'HOUNDSTOOTH', 'IG2000', 'SLAVE1', 'XANADUBLOOD', 'GAUNTLETSTARFIGHTER', 'EMPERORSSHUTTLE', 'HOUNDSTOOTH', 'EBONHAWK', 'XWINGRED3', 'XWINGRED2', 'EMPERORSSHUTTLE', 'EBONHAWK', 'COMMANDSHUTTLE', 'HOUNDSTOOTH', 'MILLENNIUMFALCONEP7' ] }
        }
      },
      middle: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'PHASMA', 'BOSSK', 'FIRSTORDERTROOPER', 'FIRSTORDEREXECUTIONER', 'FIRSTORDERSPECIALFORCESPILOT', 'DARTHREVAN', 'BOSSK', 'ZAMWESELL', 'SAVAGEOPRESS', 'DAKA', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDEREXECUTIONER', 'DARTHMALAK', 'FIRSTORDERTIEPILOT', 'FIRSTORDERTROOPER' ] },
          2: { active: true, units: [ 'EMPERORPALPATINE', 'DARTHMALAK', 'DEATHTROOPER', 'DIRECTORKRENNIC', 'SITHTROOPER', 'MOTHERTALZIN', 'DEATHTROOPER', 'GRANDADMIRALTHRAWN', 'WAMPA', 'DARTHREVAN', 'NIGHTSISTERINITIATE', 'NIGHTSISTERSPIRIT', 'BOSSK', 'SAVAGEOPRESS', 'DAKA' ] },
          3: { active: true, units: [ 'JANGOFETT', 'BOSSK', 'DARTHMALAK', 'DARTHSIDIOUS', 'DARTHREVAN', 'JANGOFETT', 'ZAMWESELL', 'IG88', 'BOSSK', 'IG86SENTINELDROID', 'DARTHREVAN', 'MOTHERTALZIN', 'IG86SENTINELDROID', 'JANGOFETT', 'NIGHTSISTERSPIRIT' ] },
          4: { active: true, units: [ 'DARTHSION', 'DARTHTRAYA', 'DARTHNIHILUS', 'DARTHREVAN', 'SITHMARAUDER', 'DENGAR', 'DARTHMALAK', 'AURRA_SING', 'BOSSK', 'BOBAFETT', 'DARTHREVAN', 'NIGHTSISTERSPIRIT', 'NIGHTSISTERZOMBIE', 'MOTHERTALZIN', 'NIGHTSISTERACOLYTE' ] },
          5: { active: true, units: [ 'MOTHERTALZIN', 'DENGAR', 'BOBAFETT', 'WAMPA', 'BOSSK', 'DARTHTRAYA', 'DARTHMALAK', 'CANDEROUSORDO', 'DARTHREVAN', 'DARTHSION', 'DARTHREVAN', 'BOSSK', 'NIGHTSISTERSPIRIT', 'SAVAGEOPRESS', 'URORRURRR' ] },
          6: { active: true, units: [ 'BASTILASHANDARK', 'CANDEROUSORDO', 'DARTHNIHILUS', 'SITHTROOPER', 'DARTHSION', 'GAMORREANGUARD', 'GARSAXON', 'GRANDADMIRALTHRAWN', 'WAMPA', 'SNOWTROOPER', 'DARTHREVAN', 'DARTHMALAK', 'JANGOFETT', 'MOTHERTALZIN', 'BOSSK' ] }
        }
      },
      bottom: {
        unitType: UnitType.CHARACTER,
        platoons: {
          1: { active: true, units: [ 'GRANDADMIRALTHRAWN', 'EMPERORPALPATINE', 'HUMANTHUG', 'DEATHTROOPER', 'MAGMATROOPER', 'DARTHREVAN', 'DARTHMALAK', 'DARTHSIDIOUS', 'KYLORENUNMASKED', 'WAMPA', 'EMPERORPALPATINE', 'VADER', 'GRANDADMIRALTHRAWN', 'MOTHERTALZIN', 'DEATHTROOPER' ] },
          2: { active: true, units: [ 'GRANDMOFFTARKIN', 'EMPERORPALPATINE', 'FIRSTORDERTIEPILOT', 'STORMTROOPER', 'BOSSK', 'MOTHERTALZIN', 'FIRSTORDEROFFICERMALE', 'FIRSTORDERSPECIALFORCESPILOT', 'FIRSTORDERTIEPILOT', 'FIRSTORDEREXECUTIONER', 'TUSKENSHAMAN', 'IG86SENTINELDROID', 'DARTHREVAN', 'BOSSK', 'DARTHMALAK' ] },
          3: { active: true, units: [ 'IMPERIALSUPERCOMMANDO', 'EMPERORPALPATINE', 'GRANDADMIRALTHRAWN', 'RANGETROOPER', 'DARTHMALAK', 'DIRECTORKRENNIC', 'DEATHTROOPER', 'GRANDADMIRALTHRAWN', 'HUMANTHUG', 'BOSSK', 'DARTHREVAN', 'GREEDO', 'DEATHTROOPER', 'FIRSTORDERTIEPILOT', 'RANGETROOPER' ] },
          4: { active: true, units: [ 'IG88', 'BOSSK', 'GAMORREANGUARD', 'HUMANTHUG', 'TUSKENRAIDER', 'BOSSK', 'DARTHSION', 'WAMPA', 'HK47', 'SITHASSASSIN', 'KYLORENUNMASKED', 'FIRSTORDEROFFICERMALE', 'DARTHREVAN', 'DARTHTRAYA', 'DARTHMALAK' ] },
          5: { active: true, units: [ 'WAMPA', 'DENGAR', 'BOSSK', 'AURRA_SING', 'DARTHREVAN', 'DARTHMALAK', 'URORRURRR', 'TUSKENRAIDER', 'WAMPA', 'GARSAXON', 'MAGMATROOPER', 'BOSSK', 'DEATHTROOPER', 'FIRSTORDERTIEPILOT', 'IMPERIALSUPERCOMMANDO' ] },
          6: { active: true, units: [ 'DARTHREVAN', 'JANGOFETT', 'MOTHERTALZIN', 'DARTHMALAK', 'MAUL', 'BASTILASHANDARK', 'CANDEROUSORDO', 'HK47', 'SITHTROOPER', 'DARTHTRAYA', 'DARTHMALAK', 'WAMPA', 'DARTHREVAN', 'JANGOFETT', 'MOTHERTALZIN' ] }
        }
      }
    }
  }
}

export default {
  DS,
  LS,
  GeonosisDS
}
